const PROJECT_MUTATION_APPENDLIST = 'PROJECT_MUTATION_APPENDLIST';
const PROJECT_MUTATION_CLEANLIST = 'PROJECT_MUTATION_CLEANLIST';
const PROJECT_MUTATION_PAGENO_PLUS = 'PROJECT_MUTATION_PAGENO_PLUS';
const PROJECT_MUTATION_PAGENO_RETURN = 'PROJECT_MUTATION_PAGENO_RETURN';
const PROJECT_MUTATION_LOADING_START = 'PROJECT_MUTATION_LOADING_START';
const PROJECT_MUTATION_LOADING_STOP = 'PROJECT_MUTATION_LOADING_STOP';
const PROJECT_ACTOPM_GETLIST = 'PROJECT_ACTOPM_GETLIST';
const PROJECT_ACTOPM_SEARCH = 'PROJECT_ACTOPM_SEARCH';
const PROJECT_ACTOPM_REFRESH = 'PROJECT_ACTOPM_REFRESH';

export default {
    PROJECT_MUTATION_APPENDLIST,
    PROJECT_MUTATION_CLEANLIST,
    PROJECT_MUTATION_PAGENO_PLUS,
    PROJECT_MUTATION_PAGENO_RETURN,
    PROJECT_MUTATION_LOADING_STOP,
    PROJECT_MUTATION_LOADING_START,
    PROJECT_ACTOPM_GETLIST,
    PROJECT_ACTOPM_SEARCH,
    PROJECT_ACTOPM_REFRESH
};